import os
from dotenv import load_dotenv

load_dotenv()

PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
PINECONE_ENVIRONMENT = os.getenv("PINECONE_ENVIRONMENT")
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME", "hackrx-aws-free")  # Default fallback
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

# AGGRESSIVE Performance Configuration for Sub-10s Response
AGGRESSIVE_MODE = True
MAX_CONCURRENT_REQUESTS = 20
CONNECTION_POOL_SIZE = 50
REQUEST_TIMEOUT = 30
EMBEDDING_BATCH_SIZE = 200
UPSERT_BATCH_SIZE = 50
QUERY_TIMEOUT = 6
LLM_TIMEOUT = 8
